version: 0.2

phases:
  build:
    commands:
      - mkdir testing-1-dir
      - mkdir testing-2-dir
      - ls -lrt
      - pwd
      - cd testing-1-dir
      - touch file1.txt
      - touch file2.txt
      - cd ..
      - cd testing-2-dir
      - touch file3.txt
      - touch file4.txt
      - cd ..
      - ls -lrt testing-1-dir
      - ls -lrt testing-2-dir
artifacts:
  files:
  secondary-artifacts:
    build_output:
      files:
        - '**/*'
      name: build_output
      discard-paths: yes
      base-directory: $CODEBUILD_SRC_DIR
    share_build_output:
      files:
        - '**/*'
      name: share_build_output
      discard-paths: yes
      base-directory: $CODEBUILD_SRC_DIR
