version: 0.2

phases:
  build:
    commands:
      - mkdir testing-1-dir
      - mkdir testing-2-dir
      - cd testing-1-dir
      - touch file1.txt
      - touch file2.txt
      - cd ..
      - cd testing-2-dir
      - touch file3.txt
      - touch file4.txt
      - cd ..

artifacts:
  files:
    - '**/*'
  secondary-artifacts:
    build_output:
    base-directory: $CODEBUILD_SRC_DIR
    files:
      - 'testing-1-dir/*'
    name: build_output
    discard-paths: yes
    share_build_output:
      base-directory: $CODEBUILD_SRC_DIR
      files:
        - 'testing-2-dir/*'
      name: share_build_output
      discard-paths: yes
